name = "BrotViz"
uuid = "b2afee0e-5ae9-4674-9c86-b31c1a479060"
authors = ["Jeffrey Wack <jeffwack111@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
